travis:
  secure:
    BINSTAR_TOKEN: UxhrZik9RZliBBLBckflLuODtdGuJsMlG+2f6A55sVVgdJGsrfme32XbDogcRMNt9MKqn8CsDSwbhTZRSMMZzua9P93Tsoc+/hUMImuS2xru8U1l3u34olQnmCbRcjTsDhdu0HUPSmHguNUCKJyYiHKzaozbH4DxFknGigxegt88OkmBQ6pmaNxZfRHhqZ6Y48+I+fsinc+xxU7QhLO9YZZUC0X9orDS6zIngCCRypWak87toxOWY/uDoO6wyzHG723fpul+7fRg3gr1nWluJ8uuL4Yqn8QBrsId5ayg+FlOh/psH2xNVGhPX7tumbWCKXKox2hbGEsvhOHTS9JQWJ+tFrV02zBv6qgjuQGr2Yy6kvIZYc/uwEUo8poP5YMoORlSmovBbymqfYnoYFNflW8/ea5PfKUMxg4p3cGNHtdmIsD2m1b8z2bIjlHQTMCbOzoPFd1KaAYQq+W51JlCHgNfTylFUGbXkJ/qvZ94bj/0JAaFbSyCtm25AQDvItQEvFIWAjvRCHnSq8O7KNRIa+rhXVEb5FyB4ur7u8T7vFfERrWfMlkSWRwyyQEdUp4mNvQcKCvCI7Tve3hRplJe1d7PvOgS9Uf1sdF9hZVeQ2IPlfNLrv9uk3zWiKIHiGan4CQpJ2oJO8n8kvuuP7xUSDIwsWYTAYS7A3KCFBVQKQA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
